/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ModernSlaveryRouteImport } from './routes/modern-slavery'
import { Route as EthicalRecruitmentRouteImport } from './routes/ethical-recruitment'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as CandidateWelfareRouteImport } from './routes/candidate-welfare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernSlaveryRoute = ModernSlaveryRouteImport.update({
  id: '/modern-slavery',
  path: '/modern-slavery',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicalRecruitmentRoute = EthicalRecruitmentRouteImport.update({
  id: '/ethical-recruitment',
  path: '/ethical-recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateWelfareRoute = CandidateWelfareRouteImport.update({
  id: '/candidate-welfare',
  path: '/candidate-welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidate-welfare': typeof CandidateWelfareRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/employers': typeof EmployersRoute
  '/ethical-recruitment': typeof EthicalRecruitmentRoute
  '/modern-slavery': typeof ModernSlaveryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidate-welfare': typeof CandidateWelfareRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/employers': typeof EmployersRoute
  '/ethical-recruitment': typeof EthicalRecruitmentRoute
  '/modern-slavery': typeof ModernSlaveryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidate-welfare': typeof CandidateWelfareRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/employers': typeof EmployersRoute
  '/ethical-recruitment': typeof EthicalRecruitmentRoute
  '/modern-slavery': typeof ModernSlaveryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/candidate-welfare'
    | '/candidates'
    | '/contact'
    | '/cookies'
    | '/employers'
    | '/ethical-recruitment'
    | '/modern-slavery'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/candidate-welfare'
    | '/candidates'
    | '/contact'
    | '/cookies'
    | '/employers'
    | '/ethical-recruitment'
    | '/modern-slavery'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/candidate-welfare'
    | '/candidates'
    | '/contact'
    | '/cookies'
    | '/employers'
    | '/ethical-recruitment'
    | '/modern-slavery'
    | '/privacy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CandidateWelfareRoute: typeof CandidateWelfareRoute
  CandidatesRoute: typeof CandidatesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EmployersRoute: typeof EmployersRoute
  EthicalRecruitmentRoute: typeof EthicalRecruitmentRoute
  ModernSlaveryRoute: typeof ModernSlaveryRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern-slavery': {
      id: '/modern-slavery'
      path: '/modern-slavery'
      fullPath: '/modern-slavery'
      preLoaderRoute: typeof ModernSlaveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethical-recruitment': {
      id: '/ethical-recruitment'
      path: '/ethical-recruitment'
      fullPath: '/ethical-recruitment'
      preLoaderRoute: typeof EthicalRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-welfare': {
      id: '/candidate-welfare'
      path: '/candidate-welfare'
      fullPath: '/candidate-welfare'
      preLoaderRoute: typeof CandidateWelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CandidateWelfareRoute: CandidateWelfareRoute,
  CandidatesRoute: CandidatesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EmployersRoute: EmployersRoute,
  EthicalRecruitmentRoute: EthicalRecruitmentRoute,
  ModernSlaveryRoute: ModernSlaveryRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
